### PR TITLE
Version bump 0.3.0 -> 0.4.1

### PR DESCRIPTION
**Pull request by goozzik**

### CODE REVIEW

**Comment by Strech** [comment]
@goozzik why 0.4.1 and why it's pushed already?

**Comment by goozzik** [comment]
@Strech 

>why 0.4.1?

I had to to update to `0.4.1` instead of `0.4.0`. At first I released the version with `0.4.0` and then removed it from the rubygems and I couldn't rerelease the same version dunno why.

> why it's pushed already?

Are we required to do the release only from master?

**Comment by Strech** [comment]
@goozzik yes, only from master. And yes you can't delete versions from rubygems, it's not NPM

**Comment by Strech** [comment]
Please next time pay some attention and write commit message properly

**Review by Strech — APPROVED** [review]
:/

**Pull request merged**
